In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from wordcloud import wordcloud

In [2]:
df=pd.read_csv("/content/drive/MyDrive/diabetes.csv")

In [3]:
df

Age  Gender Polyuria  ... Alopecia Obesity     class
0     40    Male       No  ...      Yes     Yes  Positive
1     58    Male       No  ...      Yes      No  Positive
2     41    Male      Yes  ...      Yes      No  Positive
3     45    Male       No  ...       No      No  Positive
4     60    Male      Yes  ...      Yes     Yes  Positive
..   ...     ...      ...  ...      ...     ...       ...
515   39  Female      Yes  ...       No      No  Positive
516   48  Female      Yes  ...       No      No  Positive
517   58  Female      Yes  ...       No     Yes  Positive
518   32  Female       No  ...      Yes      No  Negative
519   42    Male       No  ...       No      No  Negative

[520 rows x 17 columns]

In [4]:

df.drop(["Genital thrush","Alopecia","Obesity","partial paresis"],axis=1,inplace=True)

In [5]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
df[df['Age']==df['Age'].min()]

Age Gender Polyuria  ... delayed healing muscle stiffness     class
133   16   Male      Yes  ...              No               No  Positive

[1 rows x 13 columns]

In [7]:
x=pd.get_dummies(x)
x.head()

Age  Gender_Female  ...  muscle stiffness_No  muscle stiffness_Yes
0   40              0  ...                    0                     1
1   58              0  ...                    1                     0
2   41              0  ...                    0                     1
3   45              0  ...                    1                     0
4   60              0  ...                    0                     1

[5 rows x 23 columns]

In [8]:
x.corr()

Age  ...  muscle stiffness_Yes
Age                     1.000000  ...              0.307703
Gender_Female          -0.062872  ...              0.090542
Gender_Male             0.062872  ...             -0.090542
Polyuria_No            -0.199781  ...             -0.152938
Polyuria_Yes            0.199781  ...              0.152938
Polydipsia_No          -0.137382  ...             -0.180723
Polydipsia_Yes          0.137382  ...              0.180723
sudden weight loss_No  -0.064808  ...             -0.109756
sudden weight loss_Yes  0.064808  ...              0.109756
weakness_No            -0.224596  ...             -0.263164
weakness_Yes            0.224596  ...              0.263164
Polyphagia_No          -0.315577  ...             -0.320031
Polyphagia_Yes          0.315577  ...              0.320031
visual blurring_No     -0.402729  ...             -0.412369
visual blurring_Yes     0.402729  ...              0.412369
Itching_No             -0.296559  ...             -0.215575
Itching_Yes             0.296559  ...              0.215575
Irritability_No        -0.201625  ...             -0.201637
Irritability_Yes        0.201625  ...              0.201637
delayed healing_No     -0.257501  ...             -0.250078
delayed healing_Yes     0.257501  ...              0.250078
muscle stiffness_No    -0.307703  ...             -1.000000
muscle stiffness_Yes    0.307703  ...              1.000000

[23 rows x 23 columns]

In [ ]:
x=np.array(x)
x.shape

(520, 23)

In [ ]:
y=y.replace(('Positive','Negative'),(1,0))

In [ ]:
y

0      1
1      1
2      1
3      1
4      1
      ..
515    1
516    1
517    1
518    0
519    0
Name: class, Length: 520, dtype: int64

In [ ]:
y=np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.35,random_state=0)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
classifier=GradientBoostingClassifier()
classifier.fit(x_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
ml=ExtraTreesRegressor()
ml.fit(x,y)

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=None, oob_score=False,
                    random_state=None, verbose=0, warm_start=False)

In [ ]:
ml.feature_importances_

array([0.0523564 , 0.05299495, 0.07009886, 0.20842274, 0.2350299 ,
       0.04275084, 0.05742714, 0.03140235, 0.0292165 , 0.00357909,
       0.00405964, 0.01241583, 0.01164491, 0.01368744, 0.0125303 ,
       0.01694889, 0.01577529, 0.01237745, 0.0121581 , 0.03723007,
       0.03320327, 0.01769541, 0.01699463])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 68,   3],
       [  4, 107]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9615384615384616

In [ ]:
x_train.shape

(338, 23)

In [ ]:
import pickle
pickle_out=open('classifierk.pkl','wb')
pickle.dump(classifier,pickle_out)
pickle_out.close()

In [ ]:
def prediction(Age,Gender_Female,Gender_Male,Polyuria_No,Polyuria_Yes,Polydipsia_No,Polydipsia_Yes,suddenweightloss_No,suddenweightloss_Yes,weakness_No,weakness_Yes,Polyphagia_No,Polyphagia_Yes,visualblurring_No,visualblurring_Yes,Itching_No,Itching_Yes,Irritability_No,Irritability_Yes,delayedhealing_No,delayedhealing_Yes,musclestiffness_No,musclestiffness_Yes):
  x=[[Age,Gender_Female,Gender_Male,Polyuria_No,Polyuria_Yes,Polydipsia_No,Polydipsia_Yes,suddenweightloss_No,suddenweightloss_Yes,weakness_No,weakness_Yes,Polyphagia_No,Polyphagia_Yes,visualblurring_No,visualblurring_Yes,Itching_No,Itching_Yes,Irritability_No,Irritability_Yes,delayedhealing_No,delayedhealing_Yes,musclestiffness_No,musclestiffness_Yes]]
  cl=pickle.load(open('classifierk.pkl','rb'))
  return cl.predict(x)


In [ ]:
prediction(42,1,0,1,0,1,0,0,1,1,1,0,0,1,1,0,0,1,0,1,0,0,1)

array([1])

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,